server:
  port: 7901

spring:
  application:
    name: microservice-service-member-nacos  # 指定应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"