server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true  # 是否显示主机的IP，鼠标移动到Status列中的链接时，浏览器左下角显示出 "IP:端口号" 形式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # Status中的内容以 "IP:端口号" 形式显示
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-config-server  # 指定应用名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chenz328/microservice-config.git  # git环境地址
          search-paths:
            - client-config  # 搜索目录，可以配置多个
      label: master   # 读取分支


