server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true  # 是否显示主机的IP，鼠标移动到Status列中的链接时，浏览器左下角显示出 "IP:端口号" 形式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # Status中的内容以 "IP:端口号" 形式显示
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-service-order-feign  # 指定应用名称

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: none

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cimc.cloud.feign.MemberFeignClient: debug

ribbon:
  ReadTimeout: 5000  # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000  # 建立连接后从服务器读取到可用资源所用的时间






