server:
  port: 7901

eureka:
  instance:
    prefer-ip-address: true  # 是否显示主机的IP，鼠标移动到Status列中的链接时，浏览器左下角显示出 "IP:端口号" 形式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # Status中的内容以 "IP:端口号" 形式显示
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-service-member-zipkin  # 指定应用名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  # 采样率值介于0到1之间，1则表示全部采集

