server:
  port: 8001

spring:
  application:
    name: microservice-service-order-nacos  # 指定应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"


